# 1. Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import datetime
import time
import seaborn as sns
import matplotlib.pyplot as plt
from pymongo import MongoClient
%matplotlib inline

# 2. Connect to MongoDB Compass

In [ ]:
# Instantiate MongoDB client by localhost 27017 
client = MongoClient("mongodb://localhost:27017")

# Get database logee_trans
db = client.get_database("logee_trans")

# Retrieve collection deliveryDetails from database
deliv_details = db.get_collection("deliveryDetails")

# 3. Convert Data
Convert the retrieved .json format data into pandas dataframe.

In [ ]:
df_delivery = pd.DataFrame(list(deliv_details.find({})))

# 4. Exploratory Data Analysis (EDA)

## 1. Check Data

In [ ]:
print(df_delivery.info())
print(df_delivery.shape)
display(df_delivery.head(20))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13737 entries, 0 to 13736
Data columns (total 99 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   _id                            13737 non-null  object
 1   orderNumber                    13728 non-null  object
 2   originLatitude                 13728 non-null  object
 3   destinationAddress             13728 non-null  object
 4   distance                       13728 non-null  object
 5   originAddress                  13728 non-null  object
 6   itemHeight                     5623 non-null   float64
 7   itemValue                      13728 non-null  object
 8   destinationLocation            13728 non-null  object
 9   vehicleGroupName               13728 non-null  object
 10  itemCategoryId                 13728 non-null  object
 11  itemName                       13728 non-null  object
 12  pickupTime                     13728 non-null  object
 13  originCity                     13728 non-null  object
 14  itemWidth                      5623 non-null   float64
 15  vehicleGroupId                 13728 non-null  object
 16  destinationLatitude            13728 non-null  object
 17  itemWeight                     13728 non-null  float64
 18  sendCompanyPartnerFirst        13728 non-null  object
 19  originPicName                  13728 non-null  object
 20  itemPackage                    13728 non-null  object
 21  destinationPicPhone            13728 non-null  object
 22  destinationPicName             13728 non-null  object
 23  itemLength                     5623 non-null   float64
 24  deliveryNotes                  12141 non-null  object
 25  destinationLongitude           13728 non-null  object
 26  originLocation                 13728 non-null  object
 27  destinationCity                13728 non-null  object
 28  totalAmount                    13728 non-null  float64
 29  tripFeeAmount                  13728 non-null  float64
 30  originLongitude                13728 non-null  object
 31  originPicPhone                 13728 non-null  object
 32  taxAmount                      13728 non-null  float64
 33  deliveryDetailId               13735 non-null  object
 34  insuranceAmount                13728 non-null  float64
 35  escortId                       13728 non-null  object
 36  driverHelper                   13728 non-null  float64
 37  availableToAll                 13729 non-null  object
 38  documentId                     13696 non-null  object
 39  fulfillment                    13072 non-null  object
 40  isPaid                         13728 non-null  object
 41  isActive                       13737 non-null  bool
 42  isDeleted                      13732 non-null  object
 43  createdBy                      13728 non-null  object
 44  createdAt                      13728 non-null  object
 45  modifiedBy                     13732 non-null  object
 46  modifiedAt                     13732 non-null  object
 47  cargoCompanyId                 13728 non-null  object
 48  deliveryDetailStatus           13734 non-null  object
 49  pricingId                      408 non-null    object
 50  itemCategoryName               13723 non-null  object
 51  truckCompanyName               13716 non-null  object
 52  cargoCompanyName               13723 non-null  object
 53  truckCompanyId                 13680 non-null  object
 54  paymentOfCargoOwner            10308 non-null  object
 55  isConfirmed                    13031 non-null  object
 56  rejectionLog                   71 non-null     object
 57  deliveryOrderFile              13529 non-null  object
 58  originCargoImage               737 non-null    object
 59  destinationCargoImage          12194 non-null  object
 60  destinationCargoImageDate      12194 non-null  object
 61  receiverSignatureImage         11515 non-null  object
 62  receiverSignatureImageDate     11515 non-null  object
 63  reviewedDeliveryOrderFile      12194 non-null  object
 64  reviewedDeliveryOrderFileDate  12194 non-null  object
 65  originNotes                    13351 non-null  object
 66  destinationNotes               13351 non-null  object
 67  termsAccepted                  13356 non-null  object
 68  assignmentLetterFile           12640 non-null  object
 69  assignmentLetterFileDate       866 non-null    object
 70  cargoInvoiceDate               11218 non-null  object
 71  cargoInvoiceFile               11218 non-null  object
 72  truckInvoiceDate               11218 non-null  object
 73  truckInvoiceFile               11218 non-null  object
 74  originCargoImageDate           720 non-null    object
 75  delayTimeLimit                 13226 non-null  float64
 76  expireTimeLimit                13226 non-null  float64
 77  delayedTo                      13226 non-null  object
 78  expiredAt                      13226 non-null  object
 79  invoiceDate                    11869 non-null  object
 80  invoiceNumber                  11869 non-null  object
 81  driverNote                     517 non-null    object
 82  paymentType                    12925 non-null  object
 83  isProcessed                    12928 non-null  object
 84  paymentTypeId                  12923 non-null  object
 85  paymentTypeImage               12923 non-null  object
 86  paymentTypeName                12923 non-null  object
 87  paymentOfTruckOwner            8937 non-null   object
 88  cargoId                        29 non-null     object
 89  cargoType                      29 non-null     object
 90  containerNum                   29 non-null     object
 91  gatePassQr                     29 non-null     object
 92  userMeta                       29 non-null     object
 93  assignmentLetterDate           11746 non-null  object
 94  otpToken                       901 non-null    object
 95  truckCompanyPhone              10153 non-null  object
 96  internationalTradeType         28 non-null     object
 97  gatepass                       28 non-null     object
 98  createdByEmail                 4840 non-null   object
dtypes: bool(1), float64(11), object(87)
memory usage: 10.3+ MB
None
(13737, 99)

,_id,orderNumber,originLatitude,destinationAddress,distance,originAddress,itemHeight,itemValue,destinationLocation,vehicleGroupName,...,cargoType,containerNum,gatePassQr,userMeta,assignmentLetterDate,otpToken,truckCompanyPhone,internationalTradeType,gatepass,createdByEmail
0,5f151562f2a56c0010dd128f,LT-202007200002,-6.2382699,"Tanjung Priok, North Jakarta City, Jakarta, In...",28.0,"Bekasi, Bekasi City, West Java, Indonesia",1.0,0.0,Tanjung Priok,CDE Box,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5f437721351da9001004d1e0,LT-202008240003,-6.1021109,"Kapuk Muara, Kec. Penjaringan, Kota Jkt Utara,...",28.1,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",1.0,0.0,Kapuk Muara,Trailer Dry Container 40 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5f509dbf351da9001004d220,LT-202009030014,-6.2167736,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",52.6,"Kec. Cikupa, Tangerang, Banten, Indonesia",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5f50a5b8351da9001004d226,LT-202009030017,-6.3227303,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",75.6,"Kabupaten Karawang, Jawa Barat, Indonesia",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5f563459351da9001004d259,LT-202009070029,-6.1656824,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",29.4,"Kec. Batuceper, Kota Tangerang, Banten, Indonesia",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5f575e73351da9001004d261,LT-202009080033,-6.1656824,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",29.4,"Kec. Batuceper, Kota Tangerang, Banten, Indonesia",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5f58edeb351da9001004d271,LT-202009090041,-6.1403479,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",18.2,"Kapuk, Kecamatan Cengkareng, Kota Jakarta Bara...",1.0,0.0,Tj. Priok,Trailer Dry Container 40 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5f5df2e9c444250011e5e7c4,LT-202009130057,-6.2195686,"Kec. Danurejan, Kota Yogyakarta, Daerah Istime...",559,"Kecamatan Setiabudi, Kota Jakarta Selatan, Dae...",1.0,0.0,Kec. Danurejan,CDD Bak,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5f6054bec444250011e5e810,LT-202009150078,-6.5322491,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",51.8,"Kec. Citeureup, Bogor, Jawa Barat, Indonesia",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5f2a74cff2a56c0010dd12b3,LT-202008050002,-6.3227303,"North Jakarta, North Jakarta City, Jakarta, In...",71.3,"Karawang Regency, West Java, Indonesia",1.0,0.0,North Jakarta,Trailer Dry Container 40 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,5eff1a56e58bc77f11efba9b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5eff1a56e58bc77f11efba9c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5f15134df2a56c0010dd128d,LT-202007200001,-7.005740899999999,"Tanjung Priok, North Jakarta City, Jakarta, In...",361,"Jl. Pahlawan, Pekalongan, Jawa Tengah, Indonesia",1.0,0.0,Tanjung Priok,CDE Box,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,5f4f648b351da9001004d21c,LT-202009020012,-6.1403479,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",18.2,"Kapuk, Kecamatan Cengkareng, Kota Jakarta Bara...",1.0,0.0,Tj. Priok,Trailer Dry Container 40 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,5f521865351da9001004d234,LT-202009040024,-6.1486651,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",25.4,"Kecamatan Cengkareng, Kota Jakarta Barat, Daer...",1.0,0.0,Tj. Priok,Trailer Dry Container 40 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,5f5dc0ebc444250011e5e7b1,LT-202009130054,3.5258916,"Kec. Senen, Kota Jakarta Pusat, Daerah Khusus ...",1899,"Kec. Medan Tuntungan, Kota Medan, Sumatera Uta...",1.0,0.0,Kec. Senen,CDD Bak,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,5f604c6fc444250011e5e804,LT-202009150074,-7.2948875,"Kec. Gempol, Cirebon, Jawa Barat, Indonesia",354,"Cidadap, Sukabumi Regency, Jawa Barat, Indonesia",1.0,0.0,Kec. Gempol,Tronton Wingbox,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,5f63439bc444250011e5e840,LT-202009170093,-6.1826294,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",15.6,"Kec. Cakung, Kota Jakarta Timur, Daerah Khusus...",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,5f634a55c444250011e5e849,LT-202009170096,-6.3015658,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",71,"Karawang Barat, Kec. Karawang Bar., Kabupaten ...",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,5f6495a1c444250011e5e85b,LT-202009180101,-6.2167736,"Tj. Priok, Kota Jkt Utara, Daerah Khusus Ibuko...",52.6,"Kec. Cikupa, Tangerang, Banten, Indonesia",1.0,0.0,Tj. Priok,Trailer Dry Container 20 Feet,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Manipulation

### 1. Subset Data 1

First step is to creat subset data that only consist of column argoCompanyName, truckCompanyName, vehicleGroupName, fulfillment, and createdAt.

In [ ]:
newdeliv = df_delivery[['cargoCompanyName','truckCompanyName','vehicleGroupName','fulfillment','createdAt']]

In [ ]:
# Check information
print(newdeliv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13737 entries, 0 to 13736
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cargoCompanyName  13723 non-null  object
 1   truckCompanyName  13716 non-null  object
 2   vehicleGroupName  13728 non-null  object
 3   fulfillment       13072 non-null  object
 4   createdAt         13728 non-null  object
dtypes: object(5)
memory usage: 536.7+ KB
None

In [ ]:
print(newdeliv.shape)
display(newdeliv.head())

(13737, 5)

,cargoCompanyName,truckCompanyName,vehicleGroupName,fulfillment,createdAt
0,NaN,NaN,CDE Box,None,2020-07-20T03:54:10.304Z
1,GPI LOGISTICS,GPI LOGISTICS TRUCKER,Trailer Dry Container 40 Feet,{'driverId': '86c83cd8-2ec8-40e0-a95c-336a6c7c...,2020-08-24T08:15:29.279Z
2,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': '16469adb-7d50-41b9-aa66-67e4d2f6...,2020-09-03T07:39:43.535Z
3,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': 'aa421aa9-9594-4d00-9475-651e598a...,2020-09-03T08:13:44.226Z
4,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': '9dd65c45-e05f-4207-8fac-c00acd7c...,2020-09-07T13:23:37.738Z

### 2. Convert to pandas NA

Convert numpy nan format into pandas NA.

In [ ]:
newdeliv = newdeliv.fillna(pd.NA)

In [ ]:
newdeliv.head(500)

,cargoCompanyName,truckCompanyName,vehicleGroupName,fulfillment,createdAt
0,<NA>,<NA>,CDE Box,<NA>,2020-07-20T03:54:10.304Z
1,GPI LOGISTICS,GPI LOGISTICS TRUCKER,Trailer Dry Container 40 Feet,{'driverId': '86c83cd8-2ec8-40e0-a95c-336a6c7c...,2020-08-24T08:15:29.279Z
2,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': '16469adb-7d50-41b9-aa66-67e4d2f6...,2020-09-03T07:39:43.535Z
3,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': 'aa421aa9-9594-4d00-9475-651e598a...,2020-09-03T08:13:44.226Z
4,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': '9dd65c45-e05f-4207-8fac-c00acd7c...,2020-09-07T13:23:37.738Z
...,...,...,...,...,...
495,GPI LOGISTICS,PANCARAN DARAT TRANSPORT,Trailer Dry Container 20 Feet,{'driverId': 'bf5366e5-1847-4019-a58e-844295b9...,2020-11-18T07:48:15.557Z
496,GPI LOGISTICS,GPI LOGISTICS TRUCKER,Trailer Dry Container 40 Feet,{'driverId': '86c83cd8-2ec8-40e0-a95c-336a6c7c...,2020-10-13T12:54:57.903Z
497,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': '906a7550-d431-42e3-b814-1757b164...,2020-10-06T11:40:58.058Z
498,GPI LOGISTICS,GPI LOGISTICS TRUCKER,Trailer Dry Container 40 Feet,{'driverId': 'e4e23740-b3c9-4cfe-b62a-105a1603...,2020-10-06T13:54:04.584Z
499,AVI CARGO SERVICES,AVI LOGISTICS TRUCKER,Trailer Dry Container 20 Feet,{'driverId': '9dd65c45-e05f-4207-8fac-c00acd7c...,2020-10-09T15:29:28.826Z

### 3. Subset Data 2

Filter only records that doesn't have nan (null) values in any column. Then, rearrange data in ascending sort based on column truckCompanyName.

In [ ]:
newdeliv_notna = newdeliv.dropna(thresh=5)

In [ ]:
newdeliv_notna.sort_values(by='truckCompanyName',ascending=True,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [ ]:
newdeliv_notna.reset_index(inplace=True)

In [ ]:
newdeliv_notna.drop('index',axis=1,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4901: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [ ]:
newdeliv_notna.head()

,cargoCompanyName,truckCompanyName,vehicleGroupName,fulfillment,createdAt
0,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': 'b2f9ab38-039f-4ade-82a1-082b4146...,2021-06-17T12:52:32.792Z
1,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': '0d1fde9f-027f-4ba4-a5dd-652d07d7...,2021-06-08T08:43:11.022Z
2,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': '30191ca4-3b9d-46d3-be84-fe9ffca5...,2021-06-02T10:23:26.886Z
3,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 20 Feet,{'driverId': 'ff9897b1-587c-46d0-ab0c-c173632b...,2021-06-04T15:22:32.648Z
4,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': '962de0d0-8417-4b84-b0d5-f81180e5...,2021-06-08T08:39:55.182Z

In [ ]:
newdeliv_notna.shape

(13072, 5)

### 4. Delete unnecessary space

In [ ]:
newdeliv_notna.loc[:,'cargoCompanyName'] = newdeliv_notna.cargoCompanyName.apply(lambda x : x.strip())
newdeliv_notna.loc[:,'truckCompanyName'] = newdeliv_notna.truckCompanyName.apply(lambda x : x.strip())
newdeliv_notna.loc[:,'vehicleGroupName'] = newdeliv_notna.vehicleGroupName.apply(lambda x : x.strip())

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1951: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value

In [ ]:
newdeliv_notna.head(1500)

,cargoCompanyName,truckCompanyName,vehicleGroupName,fulfillment,createdAt
0,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': 'b2f9ab38-039f-4ade-82a1-082b4146...,2021-06-17T12:52:32.792Z
1,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': '0d1fde9f-027f-4ba4-a5dd-652d07d7...,2021-06-08T08:43:11.022Z
2,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': '30191ca4-3b9d-46d3-be84-fe9ffca5...,2021-06-02T10:23:26.886Z
3,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 20 Feet,{'driverId': 'ff9897b1-587c-46d0-ab0c-c173632b...,2021-06-04T15:22:32.648Z
4,TRI BINTANG INTER GLOBAL,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,{'driverId': '962de0d0-8417-4b84-b0d5-f81180e5...,2021-06-08T08:39:55.182Z
...,...,...,...,...,...
1495,BUMI MANFAAT GEMILANG,BUMI MANFAAT GEMILANG TRUCKER,Tronton Wingbox,{'driverId': '0076dc21-30a0-4007-a5f9-65a54ec7...,2021-04-14T12:30:56.629Z
1496,BUMI MANFAAT GEMILANG,BUMI MANFAAT GEMILANG TRUCKER,Tronton Wingbox,{'driverId': '959102a7-824b-49b2-938f-6682db1e...,2021-04-14T12:24:04.948Z
1497,BUMI MANFAAT GEMILANG,BUMI MANFAAT GEMILANG TRUCKER,Tronton Wingbox,{'driverId': 'b2c902d8-1305-4c14-ac5a-05c52edd...,2021-04-14T12:48:19.641Z
1498,BUMI MANFAAT GEMILANG,BUMI MANFAAT GEMILANG TRUCKER,Tronton Wingbox,{'driverId': '24ae71bc-9bef-45e1-8572-54748315...,2021-04-14T12:51:28.436Z
1499,BUMI MANFAAT GEMILANG,BUMI MANFAAT GEMILANG TRUCKER,Tronton Wingbox,{'driverId': '2c239e2a-de51-40eb-aa4f-f368e0a0...,2021-04-14T12:43:02.436Z

In [ ]:
newdeliv_notna.iloc[0,0]

'TRI BINTANG INTER GLOBAL'

### 5. Subset Data - 3

Create new subset data that only consist of column truckCompanyName,vehicleGroupName, and createdAt from data newdeliv_notna. 

Break data in column fulfillmnet into seperated columns. 

Concat the 2 new datas into a single new subset data.

In [ ]:
new_deliv = pd.concat([newdeliv_notna.drop(['cargoCompanyName','fulfillment'], axis=1), newdeliv_notna['fulfillment'].apply(pd.Series)], axis=1)

In [ ]:
print(new_deliv.shape)
display(new_deliv.head())

(13072, 17)

,truckCompanyName,vehicleGroupName,createdAt,driverId,driverName,driverEmail,driverPhone,vehicleId,vehiclePoliceNum,vehicleBrandName,vehicleImage,vehicleManufactureYear,tidNum,confirmedAt,confirmedBy,confirmedByEmail,confirmDate
0,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,2021-06-17T12:52:32.792Z,b2f9ab38-039f-4ade-82a1-082b41466413,NURSYAMSU,,087820723135,2192c35e-9077-4418-a680-65bcb0abbcb1,B9293TEJ,Hino,,2018.0,,2021-06-17T12:57:43.125Z,9bdf790b-252b-4a97-86cf-66656ac70fbc,dyahayuz0809@gmail.com,NaN
1,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,2021-06-08T08:43:11.022Z,0d1fde9f-027f-4ba4-a5dd-652d07d763ce,SOPIAN,,082213692725,2dc31580-945a-4175-84a3-fd8863ec1683,B9215UIX,Hino,,2016.0,,2021-06-08T08:51:18.248Z,9bdf790b-252b-4a97-86cf-66656ac70fbc,dyahayuz0809@gmail.com,NaN
2,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,2021-06-02T10:23:26.886Z,30191ca4-3b9d-46d3-be84-fe9ffca5ee98,SIHOTANG,,082246608778,2e83d5df-3614-48e5-9fee-88d0a0a5bee6,B9600UEJ,Hino,,2013.0,,2021-06-02T10:26:25.028Z,9bdf790b-252b-4a97-86cf-66656ac70fbc,dyahayuz0809@gmail.com,NaN
3,AGUNG MAKMUR JAYA,Trailer Dry Container 20 Feet,2021-06-04T15:22:32.648Z,ff9897b1-587c-46d0-ab0c-c173632bc127,IMIN,,0819277281,bc95b66b-17b4-4cef-a8e9-39c7d74d8315,B9965TEI,Hino,,2013.0,,2021-06-04T15:25:15.177Z,9bdf790b-252b-4a97-86cf-66656ac70fbc,dyahayuz0809@gmail.com,NaN
4,AGUNG MAKMUR JAYA,Trailer Dry Container 40 Feet,2021-06-08T08:39:55.182Z,962de0d0-8417-4b84-b0d5-f81180e5adf3,NANO,,0895350721107,d183b23b-eb7d-42c9-afd9-450f86e2f695,B9234UEL,Howo,,2015.0,,2021-06-08T08:49:46.961Z,9bdf790b-252b-4a97-86cf-66656ac70fbc,dyahayuz0809@gmail.com,NaN

### 6. Subset Data 4

Create new subset data that only consist of column truckCompanyName,vehiclePoliceNum, and createdAt.

In [ ]:
new_deliv = new_deliv[['truckCompanyName','vehiclePoliceNum','createdAt']]

In [ ]:
new_deliv

,truckCompanyName,vehiclePoliceNum,createdAt
0,AGUNG MAKMUR JAYA,B9293TEJ,2021-06-17T12:52:32.792Z
1,AGUNG MAKMUR JAYA,B9215UIX,2021-06-08T08:43:11.022Z
2,AGUNG MAKMUR JAYA,B9600UEJ,2021-06-02T10:23:26.886Z
3,AGUNG MAKMUR JAYA,B9965TEI,2021-06-04T15:22:32.648Z
4,AGUNG MAKMUR JAYA,B9234UEL,2021-06-08T08:39:55.182Z
...,...,...,...
13067,VARUNA TIRTA PRAKASYA TRUCKER,S9737UF,2021-05-12T06:49:54.006Z
13068,VARUNA TIRTA PRAKASYA TRUCKER,B9195SEI,2021-04-16T06:34:04.629Z
13069,VARUNA TIRTA PRAKASYA TRUCKER,S9759UH,2021-05-31T03:58:52.498Z
13070,VARUNA TIRTA PRAKASYA TRUCKER,S9318UH,2021-05-31T03:53:00.372Z
13071,VARUNA TIRTA PRAKASYA TRUCKER,S9752UH,2021-05-31T03:35:44.782Z

### 7. Final Data

Get year, month, and date information from column createdAt.

In [ ]:
# Get only year, month, and date information
def dates(x):
    return x.split('T')[0]

In [ ]:
new_deliv.loc[:,'Date'] = new_deliv.createdAt.apply(lambda x : dates(x))

In [ ]:
new_deliv

,truckCompanyName,vehiclePoliceNum,createdAt,Date
0,AGUNG MAKMUR JAYA,B9293TEJ,2021-06-17T12:52:32.792Z,2021-06-17
1,AGUNG MAKMUR JAYA,B9215UIX,2021-06-08T08:43:11.022Z,2021-06-08
2,AGUNG MAKMUR JAYA,B9600UEJ,2021-06-02T10:23:26.886Z,2021-06-02
3,AGUNG MAKMUR JAYA,B9965TEI,2021-06-04T15:22:32.648Z,2021-06-04
4,AGUNG MAKMUR JAYA,B9234UEL,2021-06-08T08:39:55.182Z,2021-06-08
...,...,...,...,...
13067,VARUNA TIRTA PRAKASYA TRUCKER,S9737UF,2021-05-12T06:49:54.006Z,2021-05-12
13068,VARUNA TIRTA PRAKASYA TRUCKER,B9195SEI,2021-04-16T06:34:04.629Z,2021-04-16
13069,VARUNA TIRTA PRAKASYA TRUCKER,S9759UH,2021-05-31T03:58:52.498Z,2021-05-31
13070,VARUNA TIRTA PRAKASYA TRUCKER,S9318UH,2021-05-31T03:53:00.372Z,2021-05-31
13071,VARUNA TIRTA PRAKASYA TRUCKER,S9752UH,2021-05-31T03:35:44.782Z,2021-05-31

In [ ]:
# new_deliv.to_excel('Insight3_Fix.xlsx')